# Generated by Django 5.2.17 on 2026-09-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_blogcategory_blogtag_blogpost_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="portfolio.skill"),
        ),
    ]
