# Generated by Django 5.2.17 on 2026-09-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_alter_resume_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
