# Generated by Django 5.2.17 on 2026-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="inquiry_type",
            field=models.CharField(
                choices=[
                    ("Job Opportunity", "Job Opportunity"),
                    ("Internship Opportunity", "Internship Opportunity"),
                    ("Freelance / Client", "Freelance / Client"),
                    ("Collaboration", "Collaboration"),
                    ("Project Discussion", "Project Discussion"),
                    ("Technical Discussion", "Technical Discussion"),
                    ("General Inquiry", "General Inquiry"),
                ],
                default="General Inquiry",
                max_length=50,
            ),
        ),
    ]
